title: Getting started with Scratch
hero_image: images/banner.png
description: Learn about Scratch and become an independent Scratch beginner.
version: 4
listed: false
copyedit: false
last_tested: "2020-11-28"
steps:
  - title: Introduction
  - title: Setting up Scratch
  - title: Introducing Scratch
  - title: What is what in Scratch
  - title: Scratch account
  - title: New project with sprites and backdrops, naming and saving
  - title: Useful code
  - title: Paint editor
  - title: Motion
  - title: Looks
  - title: Sound
  - title: Variables
  - title: Debugging
  - title: Duplicate sprites and copy code
  - title: Sharing and commenting
  - title: What next?
  - title: Block reference
