title: Getting started with Scratch
hero_image: images/banner.png
description: Learn about Scratch and become an independent Scratch beginner.
version: 4
listed: false
copyedit: false
last_tested: "2020-11-28"
steps:
  - title: Introduction
  - title: Setting up Scratch
  - title: Introducing Scratch
  - title: Using Scratch
  - title: Useful code
  - title: Block reference
  - title: Paint editor
  - title: Sound
  - title: Movement
  - title: Debugging
  - title: Accounts and saving
  - title: Backpack
  - title: Sharing and commenting
  - title: Important words
  - title: What next?
