title: getting-started-scratch
hero_image: images/banner.png
description: getting-started-scratch description
version: 4
listed: false
copyedit: false
last_tested: "2020-11-28"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
