---
title: Getting started with Scratch
hero_image: images/ScratchGuide_Banner.png
description: Learn about Scratch and develop your skills to use Scratch independently
version: 4
listed: false
copyedit: false
last_tested: '2020-11-28'
steps:
- title: Introduction
  completion: engaged
- title: Set up Scratch
- title: Set up a Scratch account
- title: The Scratch editor
- title: Your first Scratch project
- title: Motion
- title: Looks
- title: Sound
- title: Events
- title: Control
- title: Sensing
- title: Operators
- title: Variables
- title: My blocks
- title: Extensions
- title: Paint editor
- title: Sound editor
- title: Debug
- title: Editing tips
- title: Share and comment
  completion: internal
- title: Our Scratch projects
