title: Getting started with Scratch
hero_image: images/banner.png
description: Learn about Scratch and become an independent Scratch beginner.
version: 4
listed: false
copyedit: false
last_tested: "2020-11-28"
steps:
  - title: Introduction
  - title: Set up Scratch
  - title: Set up a Scratch account
  - title: The Scratch editor
  - title: Your first Scratch project
  - title: Motion
  - title: Looks
  - title: Sound
  - title: Variables
  - title: Paint editor
  - title: Debug
  - title: Duplicate sprites and copy code
  - title: Sharing and commenting
  - title: What next?
