---
title: Cychwyn arni gyda Scratch
hero_image: images/ScratchGuide_Banner.png
description: Dysgu am Scratch a datblygu dy sgiliau i ddefnyddio Scratch yn annibynnol
version: 4
listed: false
copyedit: false
last_tested: '2020-11-28'
steps:
  - 
    title: Cyflwyniad
    completion: engaged
  - 
    title: Gosod Scratch
  - 
    title: Gosod cyfrif Scratch
  - 
    title: Golygydd Scratch
  - 
    title: Dy brosiect Scratch cyntaf
  - 
    title: Symudiad
  - 
    title: Edrychiad
  - 
    title: Sain
  - 
    title: Digwyddiadau
  - 
    title: Rheoli
  - 
    title: Synhwyro
  - 
    title: Gweithredwyr
  - 
    title: Newidynnau
  - 
    title: Fy Mlociau
  - 
    title: Estyniadau
  - 
    title: Golygydd paent
  - 
    title: Golygydd sain
  - 
    title: Difa chwilod
  - 
    title: Awgrymiadau golygu
  - 
    title: Rhannu a gwneud sylwadau
    completion: internal
  - 
    title: Ein prosiectau Scratch
