---
title: Primeiros passos com Scratch
hero_image: images/ScratchGuide_Banner.png
description: Aprenda sobre o Scratch e desenvolva suas habilidades para usá-lo de forma independente
version: 4
listed: false
copyedit: false
last_tested: '2020-11-28'
steps:
  - 
    title: Introdução
  - 
    title: Configurando o Scratch
  - 
    title: Configure uma conta Scratch
  - 
    title: O editor do Scratch
  - 
    title: Seu primeiro projeto Scratch
  - 
    title: Movimento
  - 
    title: Aparência
  - 
    title: Som
  - 
    title: Eventos
  - 
    title: Controle
  - 
    title: Sensores
  - 
    title: Operadores
  - 
    title: Variáveis
  - 
    title: Meus blocos
  - 
    title: Extensões
  - 
    title: Editor Paint
  - 
    title: Editor de som
  - 
    title: Revisando seu código
  - 
    title: Dicas de edição
  - 
    title: Compartilhe e comente
  - 
    title: Nossos projetos Scratch
