---
title: Pierwsze kroki ze Scratchem
hero_image: obrazy/ScratchGuide_Banner.png
description: Dowiedz się więcej o Scratchu i rozwiń swoje umiejętności samodzielnego korzystania ze Scratcha
version: 4
listed: false
copyedit: false
last_tested: '2020-11-28'
steps:
  - 
    title: Wprowadzenie
    completion: engaged
  - 
    title: Skonfiguruj Scratch
  - 
    title: Załóż konto Scratch
  - 
    title: Edytor Scratch
  - 
    title: Twój pierwszy projekt Scratch
  - 
    title: Ruch
  - 
    title: Wygląd
  - 
    title: Dźwięk
  - 
    title: Zdarzenia
  - 
    title: Kontrola
  - 
    title: Czujniki
  - 
    title: Wyrażenia
  - 
    title: Zmienne
  - 
    title: Moje bloki
  - 
    title: Rozszerzenia
  - 
    title: Edytor Paint
  - 
    title: Edytor dźwięku
  - 
    title: Debugowanie
  - 
    title: Wskazówki dotyczące edycji
  - 
    title: Udostępniaj i komentuj
    completion: internal
  - 
    title: Nasze projekty Scratch
